services:
  symapi:
    build:
      context: .
      dockerfile: symapi.Dockerfile
      target: dev
    restart: always
    ports:
      - '8000:8000'
    networks:
      - internal
    healthcheck:
      test: ['CMD', 'curl', '-f', '-I', 'http://localhost:8000/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  web_tests:
    build:
      context: .
      dockerfile: web.Dockerfile
      target: dev
    environment:
      VITE_GRAPHQL_URL: http://symapi:8000/graphql
    networks:
      - internal
    depends_on:
      symapi:
        condition: service_healthy
    command: npx vitest --run
networks:
  internal:
    driver: bridge
