services:
  symapi:
    build:
      context: .
      dockerfile: symapi.Dockerfile
      target: dev
    restart: always
    ports:
      - '8000:8000'
  web_tests:
    build:
      context: .
      dockerfile: web.Dockerfile
      target: dev
    environment:
      VITE_GRAPHQL_URL: http://symapi:8000/graphql
    depends_on:
      symapi:
        condition: service_started
    command: npx vitest --run
