services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: hello
      MYSQL_DATABASE: ecam
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - '8080:8080'
  symapi:
    build:
      context: .
      dockerfile: symapi.Dockerfile
      target: dev
    volumes:
      - ./symapi/generated:/app/symapi/generated
    develop:
      watch:
        - path: ./requirements.txt
          action: rebuild
        - path: ./symapi
          target: /app/symapi
          action: sync
    restart: unless-stopped
    ports:
      - '8000:8000'
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
      target: dev
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./prisma
          target: /app/prisma
          action: rebuild
        - path: ./symapi/generated/schema.graphql
          target: /app/symapi/generated/schema.graphql
          action: rebuild
        - path: ./src
          target: /app/src
          action: sync
        - path: ./content
          target: /app/content
          action: sync
        - path: ./public
          target: /app/public
          action: sync
    volumes:
      - routes:/app/src/routes/\(generated\)
      - node_modules:/app/node_modules
    environment:
      VITE_AZURE_CLIENT_ID: af790946-79b3-435e-a2a1-f566e09a63f7
      VITE_AZURE_TENANT_ID: e3d6f09e-9ba9-4a36-ad75-d9039be4fe29
      VITE_AZURE_CLIENT_SECRET: cG-8Q~o_.-xtYPosirjAEZJu5alUccUrsVM2xas1
      VITE_AZURE_REDIRECT_URI: http://localhost:3000/auth/callback
      VITE_GRAPHQL_URL: http://symapi:8000/graphql
      VITE_PASSPHRASE: hello
      VITE_SESSION_SECRET: Kr2vM0bSdsPYd0cfuCul7RzWCZR0f34v
      DATABASE_URL: mysql://root:hello@db:3306/ecam
    ports:
      - '3000:3000'
      - '4000:4000'
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
  routes:
  node_modules:
